### ISSUE TITLE
Exporting slice fails every time

### ISSUE THREAD

**Issue by chrisrouse** [solicomo/export-to-icns#1]
I try to use the export slide to ICNS option and it fails every time. This is even with the default file from https://github.com/mmarfil/yoios.

**Comment by jimboroberts** [comment]
I'm having the same problem.

**Comment by solicomo** [comment]
This issue maybe caused by the spaces in the file name.

A fix is coming soon.

Thanks for your feedback.

**Comment by solicomo** [comment]
Please update and try again.

You are appreciated to tell me whether it can work or not.

**Comment by jimboroberts** [comment]
It's now exporting, but not sure how it works. My document is set-up with a number of artboards. Each dartboard is an icon that i'm working on. When I choose 'From Slice' it keeps exporting the one icon. (oddly from the middle of my artboards)

**Comment by solicomo** [comment]
It works following these steps roughly:
1. find the first artboard or exportable layer on the current page;
2. export it to an png file;
3. convert the png to several sizes, such as 16x16, 32x32...1024x1024, using `sips`; 
4. convert the pngs to icns using `iconutil`;
5. remove the tmp files;

If you use "From Artboards", you must create artboards from template "Mac App Icon".

**Comment by solicomo** [comment]
@jimboroberts Now, it chooses selected slice/artboard first.

Please check it out.
